### ISSUE TITLE
Где исходники последних релизов?

### ISSUE THREAD

**Issue by magicgoose** [overtake/TelegramSwift#163]
На сайте https://macos.telegram.org/ в Version History можно видеть, что сборка последней версии выпущена 07.03.18. (Прошло более 2х месяцев с той даты)
В этом репозитории последний коммит (на момент написания этого текста) Dec 29, 2017, и в сообщениях коммитов нет никакого упоминания последней версии (3.8).
Лицензия GPL подразумевает, что исходный код должен быть сделан доступным конечному пользователю вместе с бинарной сборкой.
Получается, что условия лицензии GPL не выполняются, или этот код можно найти где-то ещё?

**Comment by overtake** [comment]
Будут на этой неделе.

**Comment by magicgoose** [comment]
@overtake прошло 10 дней, всё ещё нет.

**Comment by saagarjha** [comment]
I'd like to remind you that this isn't how GPLv2 works: when you publish a new version of your software, and someone asks you for the source code to it, you do not have the luxury of asking them to wait. You must be able to provide the source code *immediately*. GPLv3 has a 30 day grace period for the first violation, but that does not apply to you since 1. you're under GPLv2, which has no grace period, and 2.  this doesn't appear to be the first time you've done this. It appears that the you're writing code somewhere else and occasionally dumping diffs here: just to be clear, this is a violation of the license under which you've put your code.

Plus, you're hurting yourself by not providing the source. There are people who are put off of contributing (#95) or cannot build your software (#161) because this repository is not up-to-date. What are you reasons for not keeping this repository up-to-date?

**Comment by magicgoose** [comment]
> … 1. you're under GPLv2, which has no grace period, and 2. this doesn't look to be the first time you've done this …

There's also 3. it's been already over 4 months, which is ≈4x more than 30 days.

**Comment by bieber** [comment]
> this is a violation of the license under which you've put your code.

You can't violate the license on your own code.  The author, as the copyright holder, isn't under any particular obligation to obey the terms of the GPL for their own code.  What are they going to do, sue themselves over it?

**Comment by saagarjha** [comment]
That would be true if @overtake was the exclusive owner of this code; however, as far as I'm aware he is not since he's merged in code from other people under GPLv2, to which they retain ownership. Had he not done this, he would be free to relicense his code under anything he wished, up to and including pulling the code. However, because he's taken contributions from third-party developers, he's stuck under the terms of GPLv2 because he can't relicense without their agreement to relicense the code they've contributed. So as I see it, the "violation" is that this code was taken, modified, and distributed without obeying the terms under which the contributions were made. I don't see any attempt made at getting acceptance from the other contributors on relicensing this, so given that the project is still under GPLv2, they (not me, because I have no ownership) could have a case to protect their copyright.

Even if I'm completely wrong about this, which I might be (please continue to correct me if I am!), the issues raised by others remain: the licensing situation around this project is incredibly murky, and there's a clear lack of transparency as to what's going on here. For a company that prides itself on openness, it's being pretty circumspect with this here :( I'd really love to see some clarification as to what the exact situation here is.

Obligatory disclaimer: I am not a lawyer. I have no right or intention to sue anyone here. I'm just a developer trying to make Telegram better, and the current situation is making it hard for me, and many others, to do so.

**Comment by saagarjha** [comment]
> **Moral Rights.** To the fullest extent permitted under applicable law, you hereby waive, and agree not to assert, all of your “moral rights” in or relating to your Contributions for the benefit of Telegram, its assigns, and their respective direct and indirect sublicensees.

Ouch. That's a very one-sided CLA!

Again, not a lawyer, but I *think* there might still be a chance of pushing this through if there were contributions made that were not under this CLA (some of the earlier pull requests, maybe?) or if the CLA can be shown to be invalid in certain jurisdictions (e.g. if, for example, the legal system doesn't allow for the transferral or waiver or moral rights). Ugh, this is quickly becoming a legal headache. It seems like significant effort has been into protecting Telegram's rights to behave this way. I should have guessed there would be a CLA involved…

**Comment by overtake** [comment]
source from 4.0 pushed to git.

**Comment by alex-mos** [comment]
Проблема осталась. Текущая версия в App Store – 4.3.4. В гитхабе – 4.0.

**Comment by saagarjha** [comment]
So, uh, I took another look at this project for unrelated reasons and found that you depend on a bunch of libraries in your [thrid-party](https://github.com/overtake/TelegramSwift/tree/master/thrid-party) [sic] folder. Many of these have licenses that require attribution. I don't see any of them mentioned in the app at all. Where can I find the "3rd party licenses" page in the app, @overtake?

**Comment by ZomkaDEV** [comment]
Проблема вернулась. Я даже не думала проверить были ли до меня такого рода issues. Кринж...
