### ISSUE TITLE
'Undefined error' after incorrect credentials attempts

### ISSUE THREAD

**Issue by sergeidyga-epam** [overtake/TelegramSwift#235]
Telegram for MacOs (v.4.6.1)
Steps to reproduce:
1. after first launch enter phone num and code
2. enter invalid credentials several times to get 'Too many attempts...' error message
3. go back to 'Enter your phone' initial screen
4. enter same phone
Result:
Error message 'undefined error'

<img width="649" alt="screenshot 2018-11-19 at 18 14 39" src="https://user-images.githubusercontent.com/41205504/48715990-5fcdc280-ec27-11e8-8c34-42e9660c760b.png">

**Comment by zweeltow** [comment]
Now all right i hope.

**Comment by RNTop** [comment]
I am also getting this error
how can I solve this . even I tried to login on another pc and browser . but everything is showing this error.

**Comment by martinamartini** [comment]
Also getting this error and there is no chance for a reset... No explanation...

**Comment by martinamartini** [comment]
After longer research I found to a twitter help desk run by telegram. In the FAQ's about login issues it reads under the link https://telegra.ph/Common-Login-Problems-03-12 as follows:

"Too many attempts"
If you receive an error message along the lines of "Too many attempts, please try again later", it means that you have attempted to perform some sort of action (in most cases, trying to log in) too many times recently.

In the case of logging in, you must wait 24 hours before you can try again. If you want to find out the exact amount of time left, you can do so by going to web.telegram.org, attempting to sign in, then tap the "show technical details" button. You'll see a message like FLOOD_WAIT_XXX, where XXX is the amount of seconds left before you're allowed to try again. If, after this amount of time, you cannot log in, please DM us on Twitter: @smstelegram. We are not able to manually change this limit for you, sorry; you must wait the 24 hours. So, chances are, if you message us about this, we might not even respond or just point you to this article. It's nothing personal, there's just nothing we can do -- sorry!

"But, please... I'm just trying to log in..."

We understand your pain, we truly do. Having to wait for so long to log in is really a pain in the... yeah. But there is literally nothing we can do. The Great Telegram Gods Above have not given us the power to reduce or eliminate this waiting period.

So that's all you can do. Just let us be patient and wait for 24 hours! Yes, I did the mistake. After entering the key sent to me I saw that I had registered for a two-step-identification which means you need to know your password. But that happened long ago and I could not get along with my self set hint fr the password. When I remembered the meaning of my own hint I did too manny errors and it was too late... So let's do the login on my old laptop tomorrow again. If no more message from my side will follow in this thread, my After-24-hors-ogin-attempt was successful! :) Hope these hints might be useful for some other user some day! :)

**Comment by hemantgoyal** [comment]
> After longer research I found to a twitter help desk run by telegram. In the FAQ's about login issues it reads under the link https://telegra.ph/Common-Login-Problems-03-12 as follows:
> 
> "Too many attempts"
> If you receive an error message along the lines of "Too many attempts, please try again later", it means that you have attempted to perform some sort of action (in most cases, trying to log in) too many times recently.
> 
> In the case of logging in, you must wait 24 hours before you can try again. If you want to find out the exact amount of time left, you can do so by going to web.telegram.org, attempting to sign in, then tap the "show technical details" button. You'll see a message like FLOOD_WAIT_XXX, where XXX is the amount of seconds left before you're allowed to try again. If, after this amount of time, you cannot log in, please DM us on Twitter: @smsTelegram. We are not able to manually change this limit for you, sorry; you must wait the 24 hours. So, chances are, if you message us about this, we might not even respond or just point you to this article. It's nothing personal, there's just nothing we can do -- sorry!
> 
> "But, please... I'm just trying to log in..."
> 
> We understand your pain, we truly do. Having to wait for so long to log in is really a pain in the... yeah. But there is literally nothing we can do. The Great Telegram Gods Above have not given us the power to reduce or eliminate this waiting period.
> 
> So, dear github users, that's all you can do. Just let us be patient and wait for 24 hours! Yes, I did the mistake. After entering the key sent to me I saw that I had registered for a two-step-identification which means you need to know your password. But that happened long ago and I could not get along with my self set hint for my password. These are those special moments in life, haha!!! When I remembered the meaning of my own hint I had already done too many errors and it was too late...
> 
> So I'll do the login on my old laptop tomorrow again. Thanks heaven no harm is done to my working account on my cell phone, it kept connected and I am glad. If no more message from my side will follow in this thread, it means that my After-24-hours-login-attempt was successful! :)
> 
> Hope these hints might be useful for some other user some day! :)

I am able to login to web.telegram.org but unable to do the same in my mac telegram app :/
